# Generated by Django 4.1.2 on 2022-10-14 18:57

import albums.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_rename_social_link_field_artist_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=200)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('release_datetime', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=5, max_digits=10, validators=[albums.models.costValidator])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artist')),
            ],
        ),
    ]
