# Generated by Django 4.1.2 on 2022-10-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='albums',
        ),
    ]
