# Generated by Django 4.1.2 on 2022-10-18 12:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creation_datetime',
        ),
        migrations.AddField(
            model_name='album',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='album',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
