# Generated by Django 4.1.2 on 2022-10-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
