# Generated by Django 4.1.2 on 2022-10-22 16:24

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='songs/audios', validators=[albums.models.audio_file_validator]),
        ),
    ]
