# Generated by Django 4.1.2 on 2022-10-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_remove_song_thumbnail_alter_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
